name: CI

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libunwind-dev

      - name: Build
        run: |
          make release

      - uses: actions/upload-artifact@v4
        with:
          path: |
            libSegFault.so
            tracer

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: build/bin/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
