name: CI

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]

jobs:
  build-x86_64:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libunwind-dev

      - name: Build
        run: |
          make release
          tar -C build -cJf glibc-tools-x86_64.tar.xz libSegFault.so tracer

      - name: Test
        run: |
          build/tracer --help
          export LIBSEGFAULT_TRACER="$PWD/build/tracer"
          export LIBSEGFAULT_DEBUG=1
          export LD_PRELOAD="$PWD/build/libSegFault.so"
          build/faulty-example 2>&1 | grep "faulty-example.cpp"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            glibc-tools-x86_64.tar.xz

  build-arm64:
    runs-on: [ 'self-hosted', 'ce', 'linux', 'arm64' ]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          export CC=gcc-11
          export CXX=g++-11
          make release-arm64
          tar -C build -cJf glibc-tools-arm64.tar.xz libSegFault.so tracer

      - name: Test
        run: |
          build/tracer --help
          export LIBSEGFAULT_TRACER="$PWD/build/tracer"
          export LIBSEGFAULT_DEBUG=1
          export LD_PRELOAD="$PWD/build/libSegFault.so"
          build/faulty-example

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            glibc-tools-arm64.tar.xz
