name: CI

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libunwind-dev

      - name: Build
        run: |
          make release

      - uses: actions/upload-artifact@v4
        with:
          path: |
            libSegFault.so
            tracer

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            bin/libSegFault.so
            bin/tracer
